/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WWsIdRouteImport } from './routes/w.$wsId'
import { Route as ApiDirectorRouteImport } from './routes/api/director'
import { Route as WWsIdIndexRouteImport } from './routes/w.$wsId.index'
import { Route as WWsIdPPidRouteImport } from './routes/w.$wsId.p.$pid'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WWsIdRoute = WWsIdRouteImport.update({
  id: '/w/$wsId',
  path: '/w/$wsId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDirectorRoute = ApiDirectorRouteImport.update({
  id: '/api/director',
  path: '/api/director',
  getParentRoute: () => rootRouteImport,
} as any)
const WWsIdIndexRoute = WWsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WWsIdRoute,
} as any)
const WWsIdPPidRoute = WWsIdPPidRouteImport.update({
  id: '/p/$pid',
  path: '/p/$pid',
  getParentRoute: () => WWsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/director': typeof ApiDirectorRoute
  '/w/$wsId': typeof WWsIdRouteWithChildren
  '/w/$wsId/': typeof WWsIdIndexRoute
  '/w/$wsId/p/$pid': typeof WWsIdPPidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/director': typeof ApiDirectorRoute
  '/w/$wsId': typeof WWsIdIndexRoute
  '/w/$wsId/p/$pid': typeof WWsIdPPidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/director': typeof ApiDirectorRoute
  '/w/$wsId': typeof WWsIdRouteWithChildren
  '/w/$wsId/': typeof WWsIdIndexRoute
  '/w/$wsId/p/$pid': typeof WWsIdPPidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/api/director'
    | '/w/$wsId'
    | '/w/$wsId/'
    | '/w/$wsId/p/$pid'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/api/director' | '/w/$wsId' | '/w/$wsId/p/$pid'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/api/director'
    | '/w/$wsId'
    | '/w/$wsId/'
    | '/w/$wsId/p/$pid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ApiDirectorRoute: typeof ApiDirectorRoute
  WWsIdRoute: typeof WWsIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$wsId': {
      id: '/w/$wsId'
      path: '/w/$wsId'
      fullPath: '/w/$wsId'
      preLoaderRoute: typeof WWsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/director': {
      id: '/api/director'
      path: '/api/director'
      fullPath: '/api/director'
      preLoaderRoute: typeof ApiDirectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$wsId/': {
      id: '/w/$wsId/'
      path: '/'
      fullPath: '/w/$wsId/'
      preLoaderRoute: typeof WWsIdIndexRouteImport
      parentRoute: typeof WWsIdRoute
    }
    '/w/$wsId/p/$pid': {
      id: '/w/$wsId/p/$pid'
      path: '/p/$pid'
      fullPath: '/w/$wsId/p/$pid'
      preLoaderRoute: typeof WWsIdPPidRouteImport
      parentRoute: typeof WWsIdRoute
    }
  }
}

interface WWsIdRouteChildren {
  WWsIdIndexRoute: typeof WWsIdIndexRoute
  WWsIdPPidRoute: typeof WWsIdPPidRoute
}

const WWsIdRouteChildren: WWsIdRouteChildren = {
  WWsIdIndexRoute: WWsIdIndexRoute,
  WWsIdPPidRoute: WWsIdPPidRoute,
}

const WWsIdRouteWithChildren = WWsIdRoute._addFileChildren(WWsIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ApiDirectorRoute: ApiDirectorRoute,
  WWsIdRoute: WWsIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
